aquelemiguel/parrot

- src/commands/leave.rs
- src/commands/summon.rs
> Fix leave and summon commands

- src/commands/play.rs
- src/utils.rs
> Fix incorrect estimated time until play

- CHANGELOG.md
Adds a changelog file that will be used to keep track of changes for each release.
> docs: add changelog file

- .github/workflows/main.yml
- src/commands/genius/explain.rs
- src/commands/repeat.rs
- src/events/idle_notifier.rs
| - | - |
| --- | --- |
| Issue | https://github.com/aquelemiguel/parrot/issues/60 |
| Decisions | Run clippy and fix the issues. Use clippy in the workflow from now on. Not updating changelog because it does not concern the product (parrot) itself, just a DevOps change. |
> 60: Fix clippy warnings and add it to workflow

- src/commands/summon.rs
- src/events/idle_notifier.rs
- src/strings.rs
* Closes #54.
Haven't added a command to configure the timeout as of now because I'd rather wait and see how #45 gets implemented.
Timeout is currently set to 10 minutes of no tracks playing.
> feat: auto-leave on idle

- README.md
* Update `README.md`.
Tested locally without installing `youtube-dl` and everything worked as expected.
> Update linux's `youtube-dl` installation

- src/commands/mod.rs
- src/commands/version.rs
- src/main.rs
- src/utils.rs
| - | - |
| --- | --- |
| Issue | https://github.com/aquelemiguel/parrot/issues/71 |
| Decisions | Implement `version` command. Remove bold formatting from messages according to Guru UI Master @aquelemiguel  |
> #71: Version command

- Cargo.toml
- src/commands/summon.rs
- src/events/idle_handler.rs
- src/events/mod.rs
- src/events/serenity_handler.rs
- src/main.rs
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Fixes package version<br>Renames `IdleNotifier` to `IdleHandler`<br>Creates a `SerenityHandler` module to move some code out of main<br>Renames the `General` struct to `Commands`|
> refactor: serenity and idle handlers in their modules & commands struct

- Cargo.toml
- Dockerfile
- src/client.rs
- src/lib.rs
- src/main.rs
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Abstract the creation of a parrot client so that users can use this crate and instantiate their parrot in case they want to.  |
> refactor: transfer main binary to lib code

- Cargo.toml
* fix: docker build by @joao-conde in https://github.com/aquelemiguel/parrot/pull/81
* feat: Implement docker deployment fallback by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/82
**Full Changelog**: https://github.com/aquelemiguel/parrot/compare/v0.4.0...v0.5.0
> bump: version 0.5.0

- src/commands/remove.rs
- src/events/serenity_handler.rs
Closes #93.
* Changed the tooltip:
* Added handling support for negative numbers
> remove command UX enhancement

- Cargo.toml
> deps: lock songbird version

- Cargo.lock
- Cargo.toml
* remove command UX enhancement by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/95
* #42: Command `/autopause` by @joao-conde in https://github.com/aquelemiguel/parrot/pull/98
* embeds & message refactor and tweaks by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/99
* feat: live update `/queue` by @aquelemiguel in https://github.com/aquelemiguel/parrot/pull/96
* fix: use now playing string from `strings.rs` by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/105
* deps: lock songbird version by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/108
* feat: use built-in input parsing & add `cargo.lock` by @afonsojramos in https://github.com/aquelemiguel/parrot/pull/109
* feat: drop youtube_dl crate by @aquelemiguel in …
> bump: version 1.1.0

- src/commands/summon.rs
> fix: `/play` panic in outside channel

- src/commands/play.rs
- src/commands/summon.rs
- src/handlers/serenity.rs
- src/strings.rs
- src/utils.rs
> fix: force play on same voice channel

- Cargo.lock
- Cargo.toml
- src/handlers/serenity.rs
> fix: `queue` & `np` check

- src/commands/queue.rs
- src/commands/skip.rs
- src/handlers/track_end.rs
> fix: panic on Option unwrap in `skip.rs`

- src/commands/skip.rs
> fix: `skip` accounting users connected to guild

- src/commands/play.rs
> fix: queue messages not live updating with playlist enqueue

- src/commands/mod.rs
- src/commands/play.rs
- src/sources/youtube.rs
Also renamed `PlayMode` to simply `Mode` since it is now encapsulated within the `play` command.
> chore: moved `PlayMode` and `QueryType` to `play`

- src/commands/play.rs
> fix: enqueue playlists

- src/commands/play.rs
This PR fixes an error with hidden songs being enqueued, however, it leaves open space for implementation of a ParrotError interface.
> fix: hidden songs not enqueued

- src/handlers/idle.rs
Closes #171. 
The old logic was bad, it was only counting up if the queue was empty. This means that if a track was paused, it'd never disconnect (because the queue would never clear). Now it takes into account the status of the top track.
> fix: idle disconnect based on top track status

- README.md
Add the following badge to the readme. We are currently MAYBE INSECURE :eyes:
[![dependency status](https://deps.rs/repo/github/aquelemiguel/parrot/status.svg)](https://deps.rs/repo/github/aquelemiguel/parrot)
> docs: add dependency badge

- README.md
> chore: add new badges

- src/commands/play.rs
- src/handlers/idle.rs
> fix: unexpected idle disconnects

- src/handlers/serenity.rs
> fix: leaving channel alongside other users

- Cargo.lock
- Cargo.toml
> bump: `v1.4.2`

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- src/client.rs
- src/commands/autopause.rs
- src/commands/clear.rs
- src/commands/leave.rs
- src/commands/now_playing.rs
- src/commands/pause.rs
- src/commands/play.rs
- src/commands/queue.rs
- src/commands/remove.rs
- src/commands/repeat.rs
- src/commands/resume.rs
- src/commands/seek.rs
- src/commands/shuffle.rs
- src/commands/skip.rs
- src/commands/stop.rs
- src/commands/summon.rs
- src/commands/version.rs
- src/commands/voteskip.rs
- src/errors.rs
- src/handlers/idle.rs
- src/handlers/serenity.rs
- src/messaging/message.rs
- src/utils.rs
Well, we should be good to go. There's a lot here. Needs some reviews before I'm comfortable with it.
This just rips out the permission system entirely right now. We should set some safe defaults later.
Resolves #196 
Resolves #146
> Rebase for serenity:0.11.4 and songbird:0.3.0

- README.md
This PR makes the following changes to the README:
- improve docker run command
- small text fixes
- add env var details
> docs: small readme improvements

- Cargo.lock
- Cargo.toml
- src/sources/spotify.rs
> bump: rspotify 0.11.6

- src/handlers/serenity.rs
Fixes #229.
This one is just embarrassing, please approve and let's move on. 🤡
> fix: readd autopause

- Cargo.lock
- Cargo.toml
> bump: songbird 0.3.2
