- src/events/serenity_handler.rs
- src/main.rs
- src/strings.rs
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Bot prefix does not have to be the default one. Shows correct activity now.<br>Refactor magic constant being used as the default prefix and replace its usages. |
> fix: bot activity using configured prefix

- src/tests/utils.rs
- src/utils.rs
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Add some tests to utils that are extremely easy to test, unlike commands.<br><br>Did not test messaging functions because they will be rewritten and moved out of this module soon.<br><br>Decided not to test `get_prefixes`. Doing so would require deleting existing `prefixes.json` files. This is ok in a testing environment like the CI tests, but for developers running tests locally, it would delete their `prefixes.json` which might be a problem. An option to solve this would be to give an `Option` (funny) to `get_prefixes` with the path to search for. For tests, we could redirect to a test path like `test/prefixes.json`. But that would then require, every time we call `get_prefixes` to do `get_prefixes(None)` for the …
> test: util module tests

- Cargo.toml
- Dockerfile
- src/main.rs
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Generated binary is not correct. `[lib]` annotation is not needed in `Cargo.toml` to keep using it as a library, so I just reverted. |
> fix: docker build

- .github/workflows/docker.yml
As the title implies, this PR implements a Docker Deployment Fallback.
The need for this arose from the changes made by #77, which broke the docker deployment, however, a simple `docker run` would not reveal that. As such, I've implemented a check immediately after deployment that checks for the running container. If it is running it kills the old deployment, if not it proceeds to the next step which removes all exited containers.
A successful action can be observed here: https://github.com/aquelemiguel/parrot/runs/4756107077?check_suite_focus=true
> feat: Implement docker deployment fallback

- .github/workflows/docker.yml
A workflow failed due to lack of space as we only have 10GB in our machine.  
A simple 🧹 `docker system prune -a -f` solved the problem and after the re-run of the workflow everything went well 🧹
> feat: add docker prune to docker workflow

- .github/workflows/docker.yml
- Cargo.toml
The `-qa` flag was set before the addition of the step `Remove Exited Containers` aka:
>  `docker rm $(docker ps --filter status=exited -q)`
Right now we only need the current active container, we need to change to simply `-a`.
> fix: switched `docker ps` flag

- README.md
Recently I got my hands on an Apple machine and the development tools were not, at all, on par with what was actually needed. 
Since the scripts for Linux and MacOS are still very similar, I've decided to not repeat the commands description and just separate the commands themselves.
PS: By cross-referencing information with the results of #114, I removed `libopus-dev` as well, as it seems that it comes built-in with `ffmpeg`, since in the Dockerfile this library was never present and everything still works. This assumption was double-confirmed by the following message on MacOS:
> docs: added MacOS build requirements

- Dockerfile
As a result of the recently opened #113, I decided to challenge the dependencies that were defined in the Dockerfile, and it seems that 3 of them could be removed (`m4 libssl-dev pkg-config`).
I've tested this with every Discord action that I could remember, and everything still worked without these dependencies.
> build: prune unused Docker dependencies

- .github/workflows/lint.yml
- .github/workflows/main.yml
After some investigation on [Serenity](https://github.com/serenity-rs/serenity/blob/current/.github/workflows/ci.yml)'s and [Deno](https://github.com/denoland/deno/blob/main/.github/workflows/ci.ymla#L341)'s GitHub Actions, I've taken myself to improve our own Workflows to:
- Add Clippy feedback within the PR's file changes using [clippy-check](https://github.com/actions-rs/clippy-check).
- Separate Formatting and Linting into a separate workflow to take advantage of actions parallelism and reduce action time delta.
- Remove the unnecessary `--release` profile from normal day-to-day workflows, restricting it to builds in `main` and releases.
- Add build caching so that the action does not build from scratch on every step of the job.
In the end, this resulted in cutting build times by …
> ci: Optimised CI workflows

- src/handlers/serenity.rs
| - | - |
| --- | --- |
| Issue | Closes https://github.com/aquelemiguel/parrot/issues/47 |
| Dependencies | `"Manage Roles"` permission is now required and Wiki should be updated after this merge. |
| Decisions | - Refactor code to make handlers smaller and call what they need.<br>- Set permissions for all guilds for all commands of the DJ Role.<br>- The DJ Role name can then be changed by the discord admins if they want, but I picked a default ("Parrot DJ").<br>- Parrot ensures the role exists by either using an already existing one or creating a new one.<br>- now playing, queue, play, summon and version are unrestrained |
| Animated GIF | ![dj-role-commands](https://user-images.githubusercontent.com/16060539/151027353-d4e931bd-14bb-4b56-8e77-00524e0d458d.gif) |
> feat: custom DJ Role for parrot commands

- README.md
- src/client.rs
> fix: better env loading error message

- src/commands/mod.rs
- src/commands/play.rs
- src/handlers/serenity.rs
- src/sources/youtube.rs
- src/strings.rs
* Implements `/play jump` subcommand as described by #51.
* Adds previously missing behaviours like front-pushing a playlist.
* Refactors the play logic to be much more readable.
> feat: play jump subcommand

- src/sources/youtube.rs
Switch back to default audio format as livestreaming wasn't working because of `-f bestaudio`.
(Thank you to @danrpinho for reporting this!)
> fix: revert audio format back to `webm[abr>0]/bestaudio/best`

- src/commands/play.rs
Closes #159.
* Introduces `insert_track` method for inserting a track in a specific position of the queue.
* Removes `enqueue_playlist` method.
* When working with playlists, immediately insert each track in the right position instead of rotating in the end.
> refactor: superplay logic

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- src/commands/seek.rs
- src/sources/youtube.rs
Currently the [CI's clippy is failing](https://github.com/aquelemiguel/parrot/runs/5327167853) due to the release of [Rust `1.59.0`](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html). This PR fixes those errors.
> fix: clippy for rust `1.59.0`

- src/sources/youtube.rs
Closes #88.
When streaming to the terminal, download progress logs were also getting piped to stdout and then being consumed by Songbird and fed to ffmpeg. Using the `-q` flag in yt-dlp disables these messages.
I've only tested this fix on Windows, please @afonsojramos check whether this is now okay on your Linux machine. 🙂
> fix: unresponsiveness with long songs

- Cargo.toml
We should ALWAYS lock patch versions in cargo.toml. 
Unless you can make sure that all the libraries that we depend on follow semver and that they won't introduce new features in a patch (spoiler alert, you can't - and we've actually done it more than once on our package because you don't want to bump the minor), then you should always lock the versions that you are using.
Please read more about this [here](https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277) or in another post related to this problem in any other language.
> chore: fix versions in cargo.toml

- src/handlers/serenity.rs
- src/sources/youtube.rs
- src/utils.rs
Make errors follow up messages instead of responses so they do not collide with any other responses.
Resolves #201
> fix: make errors follow up messages

- README.md
Clicking the "Linux/MacOS" link was not scrolling up the README.
> docs: fix broken link to Linux/MacOS section

- Cargo.lock
- Cargo.toml
[Serenity 0.11.5](https://github.com/serenity-rs/serenity/releases/tag/v0.11.5) was released back in July, no major changes.
> bump: serenity to 0.11.5

- src/handlers/serenity.rs
- src/utils.rs
Potential solution to #203
This makes create_embed_response clobber previous responses by default. I believe this approach is closer to intended behavior, but an alternative that some might like better is if instead of clobbering the original response it posts as a followup. Looking for feedback here.
I almost wish serenity bit the bullet here and tracked whether an interaction received a response locally. Unfortunately this was the nicest way to do this without adding another call to the discord api.
> fix: address error logging regression

- src/commands/play.rs
Resolves #207. Also removed the NotInRange check altogether as there's no real way it can fail.
> fix: `/superplay next` with an empty queue throws ParrotError::NotInRange

- .github/workflows/docker.yml
I am no longer paying for the VPS that was running parrot. It now has a self-hosted deployment that auto-updates.
> chore: deprecate docker deployment workflow

- .github/workflows/build.yml
- .github/workflows/ci_workflow.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
This PR implements the usage of a stepped workflow as well as the feature of canceling a previous job in case a new commit comes in.
Additionally, to reduce the number of packages we are pushing, we are now limiting the push action to when it is either in main branch or a tag.
PS: @aquelemiguel Before merging this PR, we should update the required checks.
We currently have 110 untagged versions. Hopefully, with this, we'll reduce this number's growth drastically.
We may also consider using [delete-old-packages#ghcrio-packages](https://github.com/SmartsquareGmbH/delete-old-packages#ghcrio-packages) or something similar.
> ci: implement usage of stepped workflow

- .github/workflows/bump.yml
Create an action that updates a Cargo.toml and Cargo.lock so that we don't need to create a branch and make then changes ourselves.
> feat: add bump action

- .dockerignore
- Dockerfile
Fixes the actual reason that caused #227, which was having the dependencies lock in the `.dockerignore`. Also adds some small QoL changes like forcing cargo to use the locked dependencies, fixing the Rust Docker image version and adding a compose file.
> ci: keep Cargo.lock

- .gitignore
- Cargo.lock
- Cargo.toml
- src/commands/autopause.rs
- src/commands/manage_sources.rs
- src/commands/play.rs
- src/commands/summon.rs
- src/errors.rs
- src/guild/settings.rs
- src/handlers/serenity.rs
| - | - |
| --- | --- |
| Issue | https://github.com/aquelemiguel/parrot/issues/124 |
| Dependencies | Add `serde` crate. |
| Decisions | Derive Serialize and Deserialize traits for the GuildSettings struct. Implement a save() and load() methods. Load when the bot is summoned. Save whenever a setting changes. Save parrot data to /data/ and settings to /data/settings. |
> feat: add guild settings de/serialization

- src/sources/youtube.rs
The warnings interfere with JSON parsing
Fixes #242
> fix: ignore yt-dlp warnings

- src/commands/play.rs
- src/sources/youtube.rs
This pull request changes the behaviour when enqueuing playlists. If there is a problem while enqueuing a track of a playlist the problematic song is skipped instead of canceling the whole process.
Also the mask for playlists in the YouTube::extract function was changed to match more playlist links.
> Enqueuing playlists: skip songs that cannot be added

- src/guild/settings.rs
| - | - |
| --- | --- |
| Issue | Somewhat related to https://github.com/aquelemiguel/parrot/issues/209 |
| Dependencies | none |
| Decisions | Users in my server found it confusing that youtu.be didn't work immediately. Since youtu.be is a first-party shortened URL provided by the "share" button on YouTube, it might make sense to just allow it by default. |
> Add youtu.be as a default domain
